export const SampleWord = "Spelling Galaxy";

export const Speech = {
  // The default voice settings for all accounts.
  voice: "com.apple.voice.compact.en-US.Samantha",
  pitch: 1,
  rate: 1,
};

// Word lists with definitions for each grade level (K-12)
// that are used for seeding the database.
export const SpellingLists = [
  {
    group: 1,
    title: 'Kindergarten',
    acronym: 'KG',
    grade: 'KG',
    color: '#FF0000',
    words: [
      { word: 'cat', definition: 'A small furry animal that purrs and meows' },
      { word: 'dog', definition: 'A friendly animal that barks and wags its tail' },
      { word: 'sun', definition: 'The bright star that gives us light during the day' },
      { word: 'run', definition: 'To move quickly on your feet' },
      { word: 'big', definition: 'Large in size' },
      { word: 'red', definition: 'A bright color like an apple or fire truck' },
      { word: 'hat', definition: 'Something you wear on your head' },
      { word: 'pen', definition: 'A tool used for writing' },
      { word: 'cup', definition: 'A container for drinking' },
      { word: 'fun', definition: 'Enjoyable and entertaining' },
      { word: 'can', definition: 'To be able to do something' },
      { word: 'see', definition: 'To look at something with your eyes' },
      { word: 'the', definition: 'A word used before nouns' },
      { word: 'and', definition: 'A word that connects two things' },
      { word: 'yes', definition: 'A positive answer' },
      { word: 'no', definition: 'A negative answer' },
      { word: 'mom', definition: 'Another word for mother' },
      { word: 'dad', definition: 'Another word for father' },
      { word: 'bed', definition: 'Where you sleep at night' },
      { word: 'toy', definition: 'Something children play with' }
    ],
  },
  {
    group: 2,
    title: '1st Grade',
    acronym: '1st',
    grade: '01',
    color: '#FF4500',
    words: [
      { word: 'apple', definition: 'A round fruit that ggroups on trees' },
      { word: 'happy', definition: 'Feeling joy or pleasure' },
      { word: 'jump', definition: 'To push yourself off the ground' },
      { word: 'book', definition: 'Pages with words bound together' },
      { word: 'play', definition: 'To have fun or engage in games' },
      { word: 'tree', definition: 'A tall plant with a trunk, branches, and leaves' },
      { word: 'ball', definition: 'A round object used in games' },
      { word: 'fish', definition: 'An animal that lives in water' },
      { word: 'rain', definition: 'Water falling from clouds' },
      { word: 'blue', definition: 'The color of the sky on a clear day' },
      { word: 'door', definition: 'An opening for entering or leaving' },
      { word: 'milk', definition: 'A white drink that comes from cows' },
      { word: 'moon', definition: 'The bright object in the night sky' },
      { word: 'star', definition: 'A bright point of light in the night sky' },
      { word: 'hand', definition: 'The part of your body at the end of your arm' },
      { word: 'home', definition: 'The place where you live' },
      { word: 'name', definition: 'What you are called' },
      { word: 'like', definition: 'To enjoy or prefer something' },
      { word: 'look', definition: 'To use your eyes to see' },
      { word: 'come', definition: 'To move toward something' }
    ],
  },
  {
    group: 2,
    title: '2nd Grade',
    acronym: '2nd',
    grade: '02',
    color: '#FFA500',
    words: [
      { word: 'friend', definition: 'Someone you like and enjoy spending time with' },
      { word: 'school', definition: 'A place where children learn' },
      { word: 'about', definition: 'Concerning or regarding' },
      { word: 'every', definition: 'All of a group or collection' },
      { word: 'family', definition: 'Parents, children, and relatives' },
      { word: 'always', definition: 'At all times; constantly' },
      { word: 'before', definition: 'Earlier than; in front of' },
      { word: 'animal', definition: 'A living creature that can move' },
      { word: 'because', definition: 'For the reason that' },
      { word: 'people', definition: 'Human beings in general' },
      { word: 'change', definition: 'To make or become different' },
      { word: 'different', definition: 'Not the same as another' },
      { word: 'another', definition: 'One more; an additional one' },
      { word: 'garden', definition: 'A place where flowers or vegetables ggroup' },
      { word: 'window', definition: 'An opening in a wall with glass' },
      { word: 'picture', definition: 'A drawing, painting, or photograph' },
      { word: 'number', definition: 'A symbol used for counting' },
      { word: 'letter', definition: 'A symbol representing a sound in writing' },
      { word: 'morning', definition: 'The early part of the day' },
      { word: 'kitchen', definition: 'A room where food is prepared' }
    ],
  },
  {
    group: 3,
    title: '3rd Grade',
    acronym: '3rd',
    grade: '03',
    color: '#FFFF00',
    words: [
      { word: 'beautiful', definition: 'Very pleasing to look at' },
      { word: 'important', definition: 'Of great significance or value' },
      { word: 'enough', definition: 'As much as needed' },
      { word: 'remember', definition: 'To recall or keep in mind' },
      { word: 'favorite', definition: 'Most liked or preferred' },
      { word: 'together', definition: 'With or in proximity to another' },
      { word: 'science', definition: 'The study of the natural world' },
      { word: 'question', definition: 'A sentence asking for information' },
      { word: 'answer', definition: 'A response to a question' },
      { word: 'language', definition: 'A system of communication using words' },
      { word: 'picture', definition: 'A visual representation or image' },
      { word: 'library', definition: 'A place where books are kept' },
      { word: 'mountain', definition: 'A very high natural elevation' },
      { word: 'adventure', definition: 'An exciting or unusual experience' },
      { word: 'terrible', definition: 'Extremely bad or serious' },
      { word: 'February', definition: 'The second month of the year' },
      { word: 'Wednesday', definition: 'The fourth day of the week' },
      { word: 'ocean', definition: 'A very large body of salt water' },
      { word: 'continue', definition: 'To keep going without stopping' },
      { word: 'beginning', definition: 'The starting point of something' }
    ],
  },
  {
    group: 3,
    title: '4th Grade',
    acronym: '4th',
    grade: '04',
    color: '#ADFF2F',
    words: [
      { word: 'appreciate', definition: 'To recognize the value or quality of something' },
      { word: 'communicate', definition: 'To share information or ideas' },
      { word: 'necessary', definition: 'Required or essential' },
      { word: 'separate', definition: 'To divide or keep apart' },
      { word: 'immediate', definition: 'Occurring without delay' },
      { word: 'environment', definition: 'The natural world or surroundings' },
      { word: 'restaurant', definition: 'A place where meals are served' },
      { word: 'government', definition: 'The system that rules a country' },
      { word: 'temperature', definition: 'How hot or cold something is' },
      { word: 'recognize', definition: 'To identify from previous experience' },
      { word: 'bicycle', definition: 'A two-wheeled vehicle powered by pedaling' },
      { word: 'character', definition: 'A person in a story or play' },
      { word: 'calendar', definition: 'A chart showing days, weeks, and months' },
      { word: 'comfortable', definition: 'Providing physical ease and relaxation' },
      { word: 'electricity', definition: 'A form of energy used for power' },
      { word: 'exercise', definition: 'Physical activity to stay healthy' },
      { word: 'guarantee', definition: 'A promise that something will happen' },
      { word: 'surprise', definition: 'Something unexpected' },
      { word: 'interrupt', definition: 'To stop someone while they are speaking' },
      { word: 'dictionary', definition: 'A book that defines words' }
    ],
  },
  {
    group: 3,
    title: '5th Grade',
    acronym: '5th',
    grade: '05',
    color: '#00FF00',
    words: [
      { word: 'accommodate', definition: 'To provide space or adjust to fit needs' },
      { word: 'achievement', definition: 'Something accomplished successfully' },
      { word: 'accidentally', definition: 'Happening by chance, not on purpose' },
      { word: 'acquaintance', definition: 'Someone you know slightly' },
      { word: 'analyze', definition: 'To examine something in detail' },
      { word: 'anonymous', definition: 'Having an unknown identity' },
      { word: 'author', definition: 'A person who writes books or articles' },
      { word: 'conscience', definition: 'Inner sense of right and wrong' },
      { word: 'democracy', definition: 'Government by the people through voting' },
      { word: 'description', definition: 'A detailed account of something' },
      { word: 'embarrass', definition: 'To cause to feel self-conscious' },
      { word: 'excerpt', definition: 'A short passage from a larger work' },
      { word: 'exceed', definition: 'To go beyond a limit' },
      { word: 'function', definition: 'The purpose or role of something' },
      { word: 'innocent', definition: 'Not guilty of a crime' },
      { word: 'longitude', definition: 'Distance east or west on Earth' },
      { word: 'magnificent', definition: 'Extremely beautiful or impressive' },
      { word: 'miniature', definition: 'A smaller version of something' },
      { word: 'prejudice', definition: 'Unfair judgment formed beforehand' },
      { word: 'privilege', definition: 'A special right or advantage' }
    ],
  },
  {
    group: 4,
    title: '6th Grade',
    acronym: '6th',
    grade: '06',
    color: '#20B2AA',
    words: [
      { word: 'abbreviation', definition: 'A shortened form of a word or phrase' },
      { word: 'adolescent', definition: 'A young person developing into an adult' },
      { word: 'ancient', definition: 'Very old, from long ago' },
      { word: 'annihilate', definition: 'To destroy completely' },
      { word: 'auxiliary', definition: 'Providing additional help or support' },
      { word: 'bibliography', definition: 'A list of sources used in research' },
      { word: 'civilization', definition: 'An advanced stage of human society' },
      { word: 'committee', definition: 'A group appointed for a specific function' },
      { word: 'controversy', definition: 'Disagreement or debate' },
      { word: 'deceive', definition: 'To cause someone to believe something false' },
      { word: 'discipline', definition: 'Training to produce self-control' },
      { word: 'eligible', definition: 'Qualified or suitable for something' },
      { word: 'enthusiasm', definition: 'Intense enjoyment or interest' },
      { word: 'existence', definition: 'The state of being real or alive' },
      { word: 'grammar', definition: 'The rules of language structure' },
      { word: 'hypocrisy', definition: 'Claiming beliefs one does not hold' },
      { word: 'inevitable', definition: 'Certain to happen; unavoidable' },
      { word: 'leisure', definition: 'Free time for enjoyment' },
      { word: 'neighbor', definition: 'A person living nearby' },
      { word: 'persistent', definition: 'Continuing despite difficulty' }
    ],
  },
  {
    group: 4,
    title: '7th Grade',
    acronym: '7th',
    grade: '07',
    color: '#00FFFF',
    words: [
      { word: 'adequate', definition: 'Sufficient for a specific requirement' },
      { word: 'ambiguous', definition: 'Having more than one possible meaning' },
      { word: 'annihilate', definition: 'To destroy utterly; obliterate' },
      { word: 'aspiration', definition: 'A hope or ambition to achieve something' },
      { word: 'coincidence', definition: 'A remarkable occurrence of events by chance' },
      { word: 'consequence', definition: 'A result or effect of an action' },
      { word: 'condemn', definition: 'To express complete disapproval' },
      { word: 'conscientious', definition: 'Careful and thorough in one\'s work' },
      { word: 'deficient', definition: 'Lacking something essential' },
      { word: 'deliberately', definition: 'Done intentionally or on purpose' },
      { word: 'discrimination', definition: 'Unfair treatment of different categories' },
      { word: 'eloquent', definition: 'Fluent and persuasive in speaking' },
      { word: 'exaggerate', definition: 'To represent something as greater than it is' },
      { word: 'foreign', definition: 'From another country' },
      { word: 'hindrance', definition: 'Something that provides resistance or delay' },
      { word: 'hypothesis', definition: 'A proposed explanation requiring testing' },
      { word: 'interpretation', definition: 'An explanation of the meaning of something' },
      { word: 'liability', definition: 'A legal responsibility or debt' },
      { word: 'maintenance', definition: 'The process of preserving a condition' },
      { word: 'neutral', definition: 'Not supporting either side in a conflict' }
    ],
  },
  {
    group: 4,
    title: '8th Grade',
    acronym: '8th',
    grade: '08',
    color: '#1E90FF',
    words: [
      { word: 'accommodate', definition: 'To provide lodging or adapt to fit' },
      { word: 'appropriate', definition: 'Suitable or proper for a circumstance' },
      { word: 'ascertain', definition: 'To find out for certain; determine' },
      { word: 'benevolent', definition: 'Well-meaning and kindly' },
      { word: 'bourgeois', definition: 'Relating to middle-class conventional values' },
      { word: 'bureaucracy', definition: 'Complex administrative system with rules' },
      { word: 'commemorate', definition: 'To recall and show respect for' },
      { word: 'concurrent', definition: 'Existing or happening at the same time' },
      { word: 'conscientious', definition: 'Wishing to do what is right' },
      { word: 'contemptuous', definition: 'Showing disdain or scorn' },
      { word: 'dilemma', definition: 'A difficult choice between two options' },
      { word: 'emphasis', definition: 'Special importance or prominence' },
      { word: 'encyclopedia', definition: 'A comprehensive reference work' },
      { word: 'facilitate', definition: 'To make an action or process easier' },
      { word: 'genuine', definition: 'Truly what it is said to be; authentic' },
      { word: 'illuminate', definition: 'To light up or clarify' },
      { word: 'indigenous', definition: 'Originating or occurring naturally in a place' },
      { word: 'indispensable', definition: 'Absolutely necessary' },
      { word: 'lieutenant', definition: 'A deputy or military officer rank' },
      { word: 'perspiration', definition: 'The process of sweating' }
    ],
  },
  {
    group: 4,
    title: '9th Grade',
    acronym: '9th',
    grade: '09',
    color: '#0000FF',
    words: [
      { word: 'acknowledgment', definition: 'Recognition of the existence or truth of something' },
      { word: 'acquiesce', definition: 'To accept reluctantly but without protest' },
      { word: 'altruistic', definition: 'Showing selfless concern for others' },
      { word: 'ambivalent', definition: 'Having mixed feelings about something' },
      { word: 'antagonist', definition: 'A person who opposes or competes' },
      { word: 'apparatus', definition: 'Equipment designed for a particular purpose' },
      { word: 'apparatus', definition: 'Technical equipment or machinery' },
      { word: 'bourgeoisie', definition: 'The middle class in society' },
      { word: 'catastrophe', definition: 'A sudden disaster causing great damage' },
      { word: 'charisma', definition: 'Compelling attractiveness or charm' },
      { word: 'collaborate', definition: 'To work jointly on an activity' },
      { word: 'connoisseur', definition: 'An expert judge in matters of taste' },
      { word: 'deteriorate', definition: 'To become progressively worse' },
      { word: 'extravagant', definition: 'Exceeding reasonable limits; lavish' },
      { word: 'facade', definition: 'The front of a building or deceptive appearance' },
      { word: 'fluctuate', definition: 'To rise and fall irregularly' },
      { word: 'imperative', definition: 'Of vital importance; crucial' },
      { word: 'inadvertent', definition: 'Not resulting from intention; accidental' },
      { word: 'jurisdiction', definition: 'Official power to make legal decisions' },
      { word: 'millennium', definition: 'A period of one thousand years' }
    ],
  },
  {
    group: 5,
    title: '10th Grade',
    acronym: '10th',
    grade: '10',
    color: '#4B0082',
    words: [
      { word: 'abhorrent', definition: 'Inspiring disgust and loathing' },
      { word: 'aesthetic', definition: 'Concerned with beauty or art' },
      { word: 'alliteration', definition: 'Repetition of initial consonant sounds' },
      { word: 'ambiguous', definition: 'Open to multiple interpretations' },
      { word: 'anonymity', definition: 'The condition of being anonymous' },
      { word: 'archaic', definition: 'Very old or old-fashioned' },
      { word: 'benign', definition: 'Gentle and harmless in effect' },
      { word: 'capricious', definition: 'Unpredictable changes of mood or behavior' },
      { word: 'circumvent', definition: 'To find a way around an obstacle' },
      { word: 'cognizant', definition: 'Having knowledge or awareness' },
      { word: 'complacent', definition: 'Showing self-satisfaction uncritically' },
      { word: 'comprehensive', definition: 'Complete and including everything' },
      { word: 'corroborate', definition: 'To confirm or give support to' },
      { word: 'cynical', definition: 'Believing people are motivated by self-interest' },
      { word: 'deference', definition: 'Respectful submission to another' },
      { word: 'discrepancy', definition: 'A lack of compatibility between facts' },
      { word: 'ecclesiastical', definition: 'Relating to the church or clergy' },
      { word: 'eloquence', definition: 'Fluent or persuasive speaking or writing' },
      { word: 'exemplary', definition: 'Serving as a desirable model' },
      { word: 'gregarious', definition: 'Fond of company; sociable' }
    ],
  },
  {
    group: 5,
    title: '11th Grade',
    acronym: '11th',
    grade: '11',
    color: '#8A2BE2',
    words: [
      { word: 'abrogate', definition: 'To repeal or do away with formally' },
      { word: 'acrimonious', definition: 'Angry and bitter in manner' },
      { word: 'assiduous', definition: 'Showing great care and perseverance' },
      { word: 'audacious', definition: 'Showing willingness to take bold risks' },
      { word: 'belligerent', definition: 'Hostile and aggressive' },
      { word: 'cacophony', definition: 'A harsh, discordant mixture of sounds' },
      { word: 'catalyst', definition: 'Something that causes change' },
      { word: 'clemency', definition: 'Mercy or lenience' },
      { word: 'coalesce', definition: 'To come together to form one mass' },
      { word: 'colloquial', definition: 'Used in ordinary conversation' },
      { word: 'commensurate', definition: 'Corresponding in size or degree' },
      { word: 'conundrum', definition: 'A confusing or difficult problem' },
      { word: 'deleterious', definition: 'Causing harm or damage' },
      { word: 'disparate', definition: 'Essentially different in kind' },
      { word: 'egregious', definition: 'Outstandingly bad; shocking' },
      { word: 'enigma', definition: 'A mysterious or puzzling person or thing' },
      { word: 'ephemeral', definition: 'Lasting for a very short time' },
      { word: 'esoteric', definition: 'Intended for a small group with specialized knowledge' },
      { word: 'idiosyncrasy', definition: 'A distinctive or peculiar feature' },
      { word: 'imperious', definition: 'Arrogant and domineering' }
    ],
  },
  {
    group: 5,
    title: '12th Grade',
    acronym: '12th',
    grade: '12',
    color: '#FF00FF',
    words: [
      { word: 'aberration', definition: 'A departure from what is normal or expected' },
      { word: 'acumen', definition: 'The ability to make quick, accurate judgments' },
      { word: 'ameliorate', definition: 'To make something bad better' },
      { word: 'anachronism', definition: 'Something belonging to a different time period' },
      { word: 'archetype', definition: 'A very typical example of a certain thing' },
      { word: 'ascetic', definition: 'Characterized by severe self-discipline' },
      { word: 'auspicious', definition: 'Conducive to success; favorable' },
      { word: 'circumlocution', definition: 'Indirect way of expressing something' },
      { word: 'dichotomy', definition: 'A division into two contrasting parts' },
      { word: 'dogmatic', definition: 'Inclined to assert opinions authoritatively' },
      { word: 'egalitarian', definition: 'Believing in equal rights for all people' },
      { word: 'elucidate', definition: 'To make something clear; explain' },
      { word: 'enervate', definition: 'To weaken or drain of energy' },
      { word: 'erudite', definition: 'Having or showing great knowledge' },
      { word: 'exacerbate', definition: 'To make a problem worse' },
      { word: 'fallacious', definition: 'Based on mistaken belief' },
      { word: 'hackneyed', definition: 'Overused and lacking originality' },
      { word: 'hegemony', definition: 'Leadership or dominance by one group' },
      { word: 'iconoclast', definition: 'A person who attacks cherished beliefs' },
      { word: 'juxtaposition', definition: 'The fact of two things being placed close together' }
    ],
  },
  {
    group: null,
    title: 'Adventure Words',
    acronym: null,
    grade: null,
    color: null,
    words: [
      { word: 'Adventure', definition: 'An exciting or unusual experience' },
      { word: 'Courage', definition: 'The ability to do something that frightens you' },
      { word: 'Discover', definition: 'To find something for the first time' },
      { word: 'Journey', definition: 'Traveling from one place to another' },
      { word: 'Whisper', definition: 'To speak very softly' },
      { word: 'Careful', definition: 'Using caution to avoid mistakes or accidents' },
      { word: 'Beautiful', definition: 'Pleasing to the senses or mind' },
      { word: 'Giggle', definition: 'To laugh in a silly or quiet way' },
      { word: 'Promise', definition: 'A declaration that you will do something' },
      { word: 'Bright', definition: 'Giving off or reflecting a lot of light; intelligent' },
    ],
  },
  {
    group: null,
    title: 'Beginner (Grades 1–3)',
    acronym: null,
    grade: null,
    color: null,
    words: [
      { word: 'Apple', definition: 'A round fruit that is red, green, or yellow' },
      { word: 'River', definition: 'A large, flowing body of water' },
      { word: 'Happy', definition: 'Feeling joy or pleasure' },
      { word: 'School', definition: 'A place where children go to learn' },
      { word: 'Under', definition: 'Below or beneath something' },
      { word: 'Friend', definition: 'A person you know and like' },
      { word: 'Magic', definition: 'The power to make impossible things happen' },
      { word: 'Bunny', definition: 'A small rabbit' },
      { word: 'Story', definition: 'A tale about real or imaginary events' },
      { word: 'Kind', definition: 'Being nice or helpful to others' },
    ],
  },
  {
    group: null,
    title: 'Intermediate (Grades 4–6)',
    acronym: null,
    grade: null,
    color: null,
    words: [
      { word: 'Knowledge', definition: 'Information or understanding gained through learning' },
      { word: 'Imagine', definition: 'To form a picture or idea in your mind' },
      { word: 'Bravery', definition: 'Showing courage when facing danger or fear' },
      { word: 'Energy', definition: 'The power needed to do work or cause chang' },
      { word: 'Invent', definition: 'To create something new' },
      { word: 'Capture', definition: 'To take control of or catch something' },
      { word: 'Arrange', definition: 'To put things in a certain order' },
      { word: 'Wonder', definition: 'To feel curiosity or amazement' },
      { word: 'Distant', definition: 'Far away in space or time' },
      { word: 'Delight', definition: 'A feeling of great pleasure' },
    ],
  },
  {
    group: null,
    title: 'Advanced (Grades 7–9)',
    acronym: null,
    grade: null,
    color: null,
    words: [
      { word: 'Analyze', definition: 'To study something closely and carefully' },
      { word: 'Mysterious', definition: 'Difficult to understand or explain' },
      { word: 'Precious', definition: 'Very valuable or special' },
      { word: 'Confident', definition: 'Sure of yourself and your abilities' },
      { word: 'Embrace', definition: 'To hold someone closely or accept an idea' },
      { word: 'Sincere', definition: 'Honest and genuine in feeling' },
      { word: 'Ambition', definition: 'A strong desire to achieve something' },
      { word: 'Resourceful', definition: 'Able to find quick and clever ways to solve problems' },
      { word: 'Persuade', definition: 'To convince someone to do or believe something' },
      { word: 'Accurate', definition: 'Correct and without mistakes' },
    ],
  },
];
