export const SampleWord = "Spelling Galaxy";

export const Speech = {
  // The default voice settings for all accounts.
  voice: "com.apple.voice.compact.en-US.Samantha",
  pitch: 1,
  rate: 1,
};

// Word lists with definitions for each grade level (K-12)
// that are used for seeding the database.
export const SpellingLists = [
  {
    group: 1,
    title: 'Kindergarten',
    acronym: 'KG',
    grade: 'KG',
    color: '#FF0000',
    words: [
      { word: 'Cat', definition: 'A small furry animal that purrs and meows' },
      { word: 'Dog', definition: 'A friendly animal that barks and wags its tail' },
      { word: 'Sun', definition: 'The bright star that gives us light during the day' },
      { word: 'Run', definition: 'To move quickly on your feet' },
      { word: 'Big', definition: 'Large in size' },
      { word: 'Red', definition: 'A bright color like an apple or fire truck' },
      { word: 'Hat', definition: 'Something you wear on your head' },
      { word: 'Pen', definition: 'A tool used for writing' },
      { word: 'Cup', definition: 'A container for drinking' },
      { word: 'Fun', definition: 'Enjoyable and entertaining' },
      { word: 'Can', definition: 'To be able to do something' },
      { word: 'See', definition: 'To look at something with your eyes' },
      { word: 'The', definition: 'A word used before nouns' },
      { word: 'And', definition: 'A word that connects two things' },
      { word: 'Yes', definition: 'A positive answer' },
      { word: 'No', definition: 'A negative answer' },
      { word: 'Mom', definition: 'Another word for mother' },
      { word: 'Dad', definition: 'Another word for father' },
      { word: 'Bed', definition: 'Where you sleep at night' },
      { word: 'Toy', definition: 'Something children play with' }
    ],
  },
  {
    group: 2,
    title: '1st Grade',
    acronym: '1st',
    grade: '01',
    color: '#FF4500',
    words: [
      { word: 'Apple', definition: 'A round fruit that ggroups on trees' },
      { word: 'Happy', definition: 'Feeling joy or pleasure' },
      { word: 'Jump', definition: 'To push yourself off the ground' },
      { word: 'Book', definition: 'Pages with words bound together' },
      { word: 'Play', definition: 'To have fun or engage in games' },
      { word: 'Tree', definition: 'A tall plant with a trunk, branches, and leaves' },
      { word: 'Ball', definition: 'A round object used in games' },
      { word: 'Fish', definition: 'An animal that lives in water' },
      { word: 'Rain', definition: 'Water falling from clouds' },
      { word: 'Blue', definition: 'The color of the sky on a clear day' },
      { word: 'Door', definition: 'An opening for entering or leaving' },
      { word: 'Milk', definition: 'A white drink that comes from cows' },
      { word: 'Moon', definition: 'The bright object in the night sky' },
      { word: 'Star', definition: 'A bright point of light in the night sky' },
      { word: 'Hand', definition: 'The part of your body at the end of your arm' },
      { word: 'Home', definition: 'The place where you live' },
      { word: 'Name', definition: 'What you are called' },
      { word: 'Like', definition: 'To enjoy or prefer something' },
      { word: 'Look', definition: 'To use your eyes to see' },
      { word: 'Come', definition: 'To move toward something' }
    ],
  },
  {
    group: 2,
    title: '2nd Grade',
    acronym: '2nd',
    grade: '02',
    color: '#FFA500',
    words: [
      { word: 'Friend', definition: 'Someone you like and enjoy spending time with' },
      { word: 'School', definition: 'A place where children learn' },
      { word: 'About', definition: 'Concerning or regarding' },
      { word: 'Every', definition: 'All of a group or collection' },
      { word: 'Family', definition: 'Parents, children, and relatives' },
      { word: 'Always', definition: 'At all times; constantly' },
      { word: 'Before', definition: 'Earlier than; in front of' },
      { word: 'Animal', definition: 'A living creature that can move' },
      { word: 'Because', definition: 'For the reason that' },
      { word: 'People', definition: 'Human beings in general' },
      { word: 'Change', definition: 'To make or become different' },
      { word: 'Different', definition: 'Not the same as another' },
      { word: 'Another', definition: 'One more; an additional one' },
      { word: 'Garden', definition: 'A place where flowers or vegetables ggroup' },
      { word: 'Window', definition: 'An opening in a wall with glass' },
      { word: 'Picture', definition: 'A drawing, painting, or photograph' },
      { word: 'Number', definition: 'A symbol used for counting' },
      { word: 'Letter', definition: 'A symbol representing a sound in writing' },
      { word: 'Morning', definition: 'The early part of the day' },
      { word: 'Kitchen', definition: 'A room where food is prepared' }
    ],
  },
  {
    group: 3,
    title: '3rd Grade',
    acronym: '3rd',
    grade: '03',
    color: '#FFFF00',
    words: [
      { word: 'Beautiful', definition: 'Very pleasing to look at' },
      { word: 'Important', definition: 'Of great significance or value' },
      { word: 'Enough', definition: 'As much as needed' },
      { word: 'Remember', definition: 'To recall or keep in mind' },
      { word: 'Favorite', definition: 'Most liked or preferred' },
      { word: 'Together', definition: 'With or in proximity to another' },
      { word: 'Science', definition: 'The study of the natural world' },
      { word: 'Question', definition: 'A sentence asking for information' },
      { word: 'Answer', definition: 'A response to a question' },
      { word: 'Language', definition: 'A system of communication using words' },
      { word: 'Picture', definition: 'A visual representation or image' },
      { word: 'Library', definition: 'A place where books are kept' },
      { word: 'Mountain', definition: 'A very high natural elevation' },
      { word: 'Adventure', definition: 'An exciting or unusual experience' },
      { word: 'Terrible', definition: 'Extremely bad or serious' },
      { word: 'February', definition: 'The second month of the year' },
      { word: 'Wednesday', definition: 'The fourth day of the week' },
      { word: 'Ocean', definition: 'A very large body of salt water' },
      { word: 'Continue', definition: 'To keep going without stopping' },
      { word: 'Beginning', definition: 'The starting point of something' }
    ],
  },
  {
    group: 3,
    title: '4th Grade',
    acronym: '4th',
    grade: '04',
    color: '#ADFF2F',
    words: [
      { word: 'Appreciate', definition: 'To recognize the value or quality of something' },
      { word: 'Communicate', definition: 'To share information or ideas' },
      { word: 'Necessary', definition: 'Required or essential' },
      { word: 'Separate', definition: 'To divide or keep apart' },
      { word: 'Immediate', definition: 'Occurring without delay' },
      { word: 'Environment', definition: 'The natural world or surroundings' },
      { word: 'Restaurant', definition: 'A place where meals are served' },
      { word: 'Government', definition: 'The system that rules a country' },
      { word: 'Temperature', definition: 'How hot or cold something is' },
      { word: 'Recognize', definition: 'To identify from previous experience' },
      { word: 'Bicycle', definition: 'A two-wheeled vehicle powered by pedaling' },
      { word: 'Character', definition: 'A person in a story or play' },
      { word: 'Calendar', definition: 'A chart showing days, weeks, and months' },
      { word: 'Comfortable', definition: 'Providing physical ease and relaxation' },
      { word: 'Electricity', definition: 'A form of energy used for power' },
      { word: 'Exercise', definition: 'Physical activity to stay healthy' },
      { word: 'Guarantee', definition: 'A promise that something will happen' },
      { word: 'Surprise', definition: 'Something unexpected' },
      { word: 'Interrupt', definition: 'To stop someone while they are speaking' },
      { word: 'Dictionary', definition: 'A book that defines words' }
    ],
  },
  {
    group: 3,
    title: '5th Grade',
    acronym: '5th',
    grade: '05',
    color: '#00FF00',
    words: [
      { word: 'Accommodate', definition: 'To provide space or adjust to fit needs' },
      { word: 'Achievement', definition: 'Something accomplished successfully' },
      { word: 'Accidentally', definition: 'Happening by chance, not on purpose' },
      { word: 'Acquaintance', definition: 'Someone you know slightly' },
      { word: 'Analyze', definition: 'To examine something in detail' },
      { word: 'Anonymous', definition: 'Having an unknown identity' },
      { word: 'Author', definition: 'A person who writes books or articles' },
      { word: 'Conscience', definition: 'Inner sense of right and wrong' },
      { word: 'Democracy', definition: 'Government by the people through voting' },
      { word: 'Description', definition: 'A detailed account of something' },
      { word: 'Embarrass', definition: 'To cause to feel self-conscious' },
      { word: 'Excerpt', definition: 'A short passage from a larger work' },
      { word: 'Exceed', definition: 'To go beyond a limit' },
      { word: 'Function', definition: 'The purpose or role of something' },
      { word: 'Innocent', definition: 'Not guilty of a crime' },
      { word: 'Longitude', definition: 'Distance east or west on Earth' },
      { word: 'Magnificent', definition: 'Extremely beautiful or impressive' },
      { word: 'Miniature', definition: 'A smaller version of something' },
      { word: 'Prejudice', definition: 'Unfair judgment formed beforehand' },
      { word: 'Privilege', definition: 'A special right or advantage' }
    ],
  },
  {
    group: 4,
    title: '6th Grade',
    acronym: '6th',
    grade: '06',
    color: '#20B2AA',
    words: [
      { word: 'Abbreviation', definition: 'A shortened form of a word or phrase' },
      { word: 'Adolescent', definition: 'A young person developing into an adult' },
      { word: 'Ancient', definition: 'Very old, from long ago' },
      { word: 'Annihilate', definition: 'To destroy completely' },
      { word: 'Auxiliary', definition: 'Providing additional help or support' },
      { word: 'Bibliography', definition: 'A list of sources used in research' },
      { word: 'Civilization', definition: 'An advanced stage of human society' },
      { word: 'Committee', definition: 'A group appointed for a specific function' },
      { word: 'Controversy', definition: 'Disagreement or debate' },
      { word: 'Deceive', definition: 'To cause someone to believe something false' },
      { word: 'Discipline', definition: 'Training to produce self-control' },
      { word: 'Eligible', definition: 'Qualified or suitable for something' },
      { word: 'Enthusiasm', definition: 'Intense enjoyment or interest' },
      { word: 'Existence', definition: 'The state of being real or alive' },
      { word: 'Grammar', definition: 'The rules of language structure' },
      { word: 'Hypocrisy', definition: 'Claiming beliefs one does not hold' },
      { word: 'Inevitable', definition: 'Certain to happen; unavoidable' },
      { word: 'Leisure', definition: 'Free time for enjoyment' },
      { word: 'Neighbor', definition: 'A person living nearby' },
      { word: 'Persistent', definition: 'Continuing despite difficulty' }
    ],
  },
  {
    group: 4,
    title: '7th Grade',
    acronym: '7th',
    grade: '07',
    color: '#00FFFF',
    words: [
      { word: 'Adequate', definition: 'Sufficient for a specific requirement' },
      { word: 'Ambiguous', definition: 'Having more than one possible meaning' },
      { word: 'Annihilate', definition: 'To destroy utterly; obliterate' },
      { word: 'Aspiration', definition: 'A hope or ambition to achieve something' },
      { word: 'Coincidence', definition: 'A remarkable occurrence of events by chance' },
      { word: 'Consequence', definition: 'A result or effect of an action' },
      { word: 'Condemn', definition: 'To express complete disapproval' },
      { word: 'Conscientious', definition: 'Careful and thorough in one\'s work' },
      { word: 'Deficient', definition: 'Lacking something essential' },
      { word: 'Deliberately', definition: 'Done intentionally or on purpose' },
      { word: 'Discrimination', definition: 'Unfair treatment of different categories' },
      { word: 'Eloquent', definition: 'Fluent and persuasive in speaking' },
      { word: 'Exaggerate', definition: 'To represent something as greater than it is' },
      { word: 'Foreign', definition: 'From another country' },
      { word: 'Hindrance', definition: 'Something that provides resistance or delay' },
      { word: 'Hypothesis', definition: 'A proposed explanation requiring testing' },
      { word: 'Interpretation', definition: 'An explanation of the meaning of something' },
      { word: 'Liability', definition: 'A legal responsibility or debt' },
      { word: 'Maintenance', definition: 'The process of preserving a condition' },
      { word: 'Neutral', definition: 'Not supporting either side in a conflict' }
    ],
  },
  {
    group: 4,
    title: '8th Grade',
    acronym: '8th',
    grade: '08',
    color: '#1E90FF',
    words: [
      { word: 'Accommodate', definition: 'To provide lodging or adapt to fit' },
      { word: 'Appropriate', definition: 'Suitable or proper for a circumstance' },
      { word: 'Ascertain', definition: 'To find out for certain; determine' },
      { word: 'Benevolent', definition: 'Well-meaning and kindly' },
      { word: 'Bourgeois', definition: 'Relating to middle-class conventional values' },
      { word: 'Bureaucracy', definition: 'Complex administrative system with rules' },
      { word: 'Commemorate', definition: 'To recall and show respect for' },
      { word: 'Concurrent', definition: 'Existing or happening at the same time' },
      { word: 'Conscientious', definition: 'Wishing to do what is right' },
      { word: 'Contemptuous', definition: 'Showing disdain or scorn' },
      { word: 'Dilemma', definition: 'A difficult choice between two options' },
      { word: 'Emphasis', definition: 'Special importance or prominence' },
      { word: 'Encyclopedia', definition: 'A comprehensive reference work' },
      { word: 'Facilitate', definition: 'To make an action or process easier' },
      { word: 'Genuine', definition: 'Truly what it is said to be; authentic' },
      { word: 'Illuminate', definition: 'To light up or clarify' },
      { word: 'Indigenous', definition: 'Originating or occurring naturally in a place' },
      { word: 'Indispensable', definition: 'Absolutely necessary' },
      { word: 'Lieutenant', definition: 'A deputy or military officer rank' },
      { word: 'Perspiration', definition: 'The process of sweating' }
    ],
  },
  {
    group: 4,
    title: '9th Grade',
    acronym: '9th',
    grade: '09',
    color: '#0000FF',
    words: [
      { word: 'Acknowledgment', definition: 'Recognition of the existence or truth of something' },
      { word: 'Acquiesce', definition: 'To accept reluctantly but without protest' },
      { word: 'Altruistic', definition: 'Showing selfless concern for others' },
      { word: 'Ambivalent', definition: 'Having mixed feelings about something' },
      { word: 'Antagonist', definition: 'A person who opposes or competes' },
      { word: 'Apparatus', definition: 'Equipment designed for a particular purpose' },
      { word: 'Apparatus', definition: 'Technical equipment or machinery' },
      { word: 'Bourgeoisie', definition: 'The middle class in society' },
      { word: 'Catastrophe', definition: 'A sudden disaster causing great damage' },
      { word: 'Charisma', definition: 'Compelling attractiveness or charm' },
      { word: 'Collaborate', definition: 'To work jointly on an activity' },
      { word: 'Connoisseur', definition: 'An expert judge in matters of taste' },
      { word: 'Deteriorate', definition: 'To become progressively worse' },
      { word: 'Extravagant', definition: 'Exceeding reasonable limits; lavish' },
      { word: 'Facade', definition: 'The front of a building or deceptive appearance' },
      { word: 'Fluctuate', definition: 'To rise and fall irregularly' },
      { word: 'Imperative', definition: 'Of vital importance; crucial' },
      { word: 'Inadvertent', definition: 'Not resulting from intention; accidental' },
      { word: 'Jurisdiction', definition: 'Official power to make legal decisions' },
      { word: 'Millennium', definition: 'A period of one thousand years' }
    ],
  },
  {
    group: 5,
    title: '10th Grade',
    acronym: '10th',
    grade: '10',
    color: '#4B0082',
    words: [
      { word: 'Abhorrent', definition: 'Inspiring disgust and loathing' },
      { word: 'Aesthetic', definition: 'Concerned with beauty or art' },
      { word: 'Alliteration', definition: 'Repetition of initial consonant sounds' },
      { word: 'Ambiguous', definition: 'Open to multiple interpretations' },
      { word: 'Anonymity', definition: 'The condition of being anonymous' },
      { word: 'Archaic', definition: 'Very old or old-fashioned' },
      { word: 'Benign', definition: 'Gentle and harmless in effect' },
      { word: 'Capricious', definition: 'Unpredictable changes of mood or behavior' },
      { word: 'Circumvent', definition: 'To find a way around an obstacle' },
      { word: 'Cognizant', definition: 'Having knowledge or awareness' },
      { word: 'Complacent', definition: 'Showing self-satisfaction uncritically' },
      { word: 'Comprehensive', definition: 'Complete and including everything' },
      { word: 'Corroborate', definition: 'To confirm or give support to' },
      { word: 'Cynical', definition: 'Believing people are motivated by self-interest' },
      { word: 'Deference', definition: 'Respectful submission to another' },
      { word: 'Discrepancy', definition: 'A lack of compatibility between facts' },
      { word: 'Ecclesiastical', definition: 'Relating to the church or clergy' },
      { word: 'Eloquence', definition: 'Fluent or persuasive speaking or writing' },
      { word: 'Exemplary', definition: 'Serving as a desirable model' },
      { word: 'Gregarious', definition: 'Fond of company; sociable' }
    ],
  },
  {
    group: 5,
    title: '11th Grade',
    acronym: '11th',
    grade: '11',
    color: '#8A2BE2',
    words: [
      { word: 'Abrogate', definition: 'To repeal or do away with formally' },
      { word: 'Acrimonious', definition: 'Angry and bitter in manner' },
      { word: 'Assiduous', definition: 'Showing great care and perseverance' },
      { word: 'Audacious', definition: 'Showing willingness to take bold risks' },
      { word: 'Belligerent', definition: 'Hostile and aggressive' },
      { word: 'Cacophony', definition: 'A harsh, discordant mixture of sounds' },
      { word: 'Catalyst', definition: 'Something that causes change' },
      { word: 'Clemency', definition: 'Mercy or lenience' },
      { word: 'Coalesce', definition: 'To come together to form one mass' },
      { word: 'Colloquial', definition: 'Used in ordinary conversation' },
      { word: 'Commensurate', definition: 'Corresponding in size or degree' },
      { word: 'Conundrum', definition: 'A confusing or difficult problem' },
      { word: 'Deleterious', definition: 'Causing harm or damage' },
      { word: 'Disparate', definition: 'Essentially different in kind' },
      { word: 'Egregious', definition: 'Outstandingly bad; shocking' },
      { word: 'Enigma', definition: 'A mysterious or puzzling person or thing' },
      { word: 'Ephemeral', definition: 'Lasting for a very short time' },
      { word: 'Esoteric', definition: 'Intended for a small group with specialized knowledge' },
      { word: 'Idiosyncrasy', definition: 'A distinctive or peculiar feature' },
      { word: 'Imperious', definition: 'Arrogant and domineering' }
    ],
  },
  {
    group: 5,
    title: '12th Grade',
    acronym: '12th',
    grade: '12',
    color: '#FF00FF',
    words: [
      { word: 'Aberration', definition: 'A departure from what is normal or expected' },
      { word: 'Acumen', definition: 'The ability to make quick, accurate judgments' },
      { word: 'Ameliorate', definition: 'To make something bad better' },
      { word: 'Anachronism', definition: 'Something belonging to a different time period' },
      { word: 'Archetype', definition: 'A very typical example of a certain thing' },
      { word: 'Ascetic', definition: 'Characterized by severe self-discipline' },
      { word: 'Auspicious', definition: 'Conducive to success; favorable' },
      { word: 'Circumlocution', definition: 'Indirect way of expressing something' },
      { word: 'Dichotomy', definition: 'A division into two contrasting parts' },
      { word: 'Dogmatic', definition: 'Inclined to assert opinions authoritatively' },
      { word: 'Egalitarian', definition: 'Believing in equal rights for all people' },
      { word: 'Elucidate', definition: 'To make something clear; explain' },
      { word: 'Enervate', definition: 'To weaken or drain of energy' },
      { word: 'Erudite', definition: 'Having or showing great knowledge' },
      { word: 'Exacerbate', definition: 'To make a problem worse' },
      { word: 'Fallacious', definition: 'Based on mistaken belief' },
      { word: 'Hackneyed', definition: 'Overused and lacking originality' },
      { word: 'Hegemony', definition: 'Leadership or dominance by one group' },
      { word: 'Iconoclast', definition: 'A person who attacks cherished beliefs' },
      { word: 'Juxtaposition', definition: 'The fact of two things being placed close together' }
    ],
  },
  {
    group: null,
    title: 'Adventure Words',
    acronym: null,
    grade: null,
    color: null,
    words: [
      { word: 'Adventure', definition: 'An exciting or unusual experience' },
      { word: 'Courage', definition: 'The ability to do something that frightens you' },
      { word: 'Discover', definition: 'To find something for the first time' },
      { word: 'Journey', definition: 'Traveling from one place to another' },
      { word: 'Whisper', definition: 'To speak very softly' },
      { word: 'Careful', definition: 'Using caution to avoid mistakes or accidents' },
      { word: 'Beautiful', definition: 'Pleasing to the senses or mind' },
      { word: 'Giggle', definition: 'To laugh in a silly or quiet way' },
      { word: 'Promise', definition: 'A declaration that you will do something' },
      { word: 'Bright', definition: 'Giving off or reflecting a lot of light; intelligent' },
    ],
  },
  {
    group: null,
    title: 'Beginner (Grades 1–3)',
    acronym: null,
    grade: null,
    color: null,
    words: [
      { word: 'Apple', definition: 'A round fruit that is red, green, or yellow' },
      { word: 'River', definition: 'A large, flowing body of water' },
      { word: 'Happy', definition: 'Feeling joy or pleasure' },
      { word: 'School', definition: 'A place where children go to learn' },
      { word: 'Under', definition: 'Below or beneath something' },
      { word: 'Friend', definition: 'A person you know and like' },
      { word: 'Magic', definition: 'The power to make impossible things happen' },
      { word: 'Bunny', definition: 'A small rabbit' },
      { word: 'Story', definition: 'A tale about real or imaginary events' },
      { word: 'Kind', definition: 'Being nice or helpful to others' },
    ],
  },
  {
    group: null,
    title: 'Intermediate (Grades 4–6)',
    acronym: null,
    grade: null,
    color: null,
    words: [
      { word: 'Knowledge', definition: 'Information or understanding gained through learning' },
      { word: 'Imagine', definition: 'To form a picture or idea in your mind' },
      { word: 'Bravery', definition: 'Showing courage when facing danger or fear' },
      { word: 'Energy', definition: 'The power needed to do work or cause chang' },
      { word: 'Invent', definition: 'To create something new' },
      { word: 'Capture', definition: 'To take control of or catch something' },
      { word: 'Arrange', definition: 'To put things in a certain order' },
      { word: 'Wonder', definition: 'To feel curiosity or amazement' },
      { word: 'Distant', definition: 'Far away in space or time' },
      { word: 'Delight', definition: 'A feeling of great pleasure' },
    ],
  },
  {
    group: null,
    title: 'Advanced (Grades 7–9)',
    acronym: null,
    grade: null,
    color: null,
    words: [
      { word: 'Analyze', definition: 'To study something closely and carefully' },
      { word: 'Mysterious', definition: 'Difficult to understand or explain' },
      { word: 'Precious', definition: 'Very valuable or special' },
      { word: 'Confident', definition: 'Sure of yourself and your abilities' },
      { word: 'Embrace', definition: 'To hold someone closely or accept an idea' },
      { word: 'Sincere', definition: 'Honest and genuine in feeling' },
      { word: 'Ambition', definition: 'A strong desire to achieve something' },
      { word: 'Resourceful', definition: 'Able to find quick and clever ways to solve problems' },
      { word: 'Persuade', definition: 'To convince someone to do or believe something' },
      { word: 'Accurate', definition: 'Correct and without mistakes' },
    ],
  },
];
